import type { Affinity } from "../types/pollster";

export const affinityDescriptions: Record<Affinity, string> = {
  lawful: "Ordered and disciplined, following structure, tradition, and consistent craft.",
  evil: "Dark, menacing, or morally corrupt — unafraid to dwell in shadow.",
  balanced: "Even-handed and measured, blending contrasting qualities into a cohesive whole.",
  chaotic: "Unpredictable and unruly, thriving on disorder and surprise.",
  neutral: "Understated and detached, neither leaning light nor dark.",
  melancholic: "Contemplative and sorrowful, often tinged with longing or quiet grief.",
  fragile: "Delicate and tender, carrying a sense of vulnerability that could break at any moment.",
  transcendent: "Reaching beyond the ordinary into something vast, spiritual, or sublime.",
  ethereal: "Otherworldly and weightless, shimmering with ghostly beauty.",
  passionate: "Burning with feeling — earnest, devoted, and emotionally charged.",
  introspective: "Inward-looking and reflective, probing personal thought and memory.",
  minimalistic: "Stripped down to essentials, finding power in restraint and empty space.",
  soulful: "Deeply expressive, rooted in heartfelt emotion and human warmth.",
  dynamic: "Shifting and kinetic, moving between extremes of intensity and stillness.",
  haunting: "Lingering and eerie, leaving an unsettled impression long after it ends.",
  poetic: "Lyrical and image-rich, prioritizing metaphor, rhythm, and meaning.",
  delicate: "Soft and precise, handled with a gentle, careful touch.",
  energetic: "High-voltage and propulsive, packed with momentum and drive.",
  wistful: "Tinged with gentle nostalgia and a bittersweet longing for what's past.",
  bitter: "Sharp and resentful, steeped in regret, anger, or disillusionment.",
  counterphobic: "Confronting fear head-on, turning dread into fuel for boldness.",
  adventurous: "Curious and exploratory, eager to chart unfamiliar territory.",
  wild: "Untamed and feral, raw in both sound and spirit.",
  courageous: "Brave and unflinching, willing to face hard truths or risks.",
  determined: "Focused and resolute, driving toward a goal without wavering.",
  unique: "Singular and idiosyncratic, resisting easy comparison.",
  defiant: "Resistant and rebellious, pushing back against expectation or authority.",
  intense: "Heavy and all-consuming, demanding the listener's full attention.",
  righteous: "Morally charged and principled, carrying a sense of justice or conviction.",
  moralistic: "Preoccupied with right and wrong, weighing values openly.",
  quiet: "Hushed and intimate, speaking in whispers rather than shouts.",
  dominant: "Commanding and assertive, taking up space with confidence.",
};
